### ISSUE TITLE
Project lacks license

### ISSUE THREAD

**Issue by tryoxiss** [ttocsneb/mbon#9]
Standard IANAL disclaimer.

The project currently has no licence, and one will need to be chosen or else nobody would be able to legally use the library. The rust community overwhelmingly dual-licenses under [MIT](https://mit-license.org/) and [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0.html), allowing end users to use whichever set of terms they prefer. These are very simple licences, allowing for use in any application of any kind, FOSS or properietary, without fee, so long as a licence disclaimer and credit is included with all distributions.

Apache 2.0 is basically the same, but with the addition of an explicit patent licence (meaning any patented code is granted the licence along with averything else), at the cost of needing to state changes made to the software.

Due to thier similarity and broad compatability, most programs are dual-licenced under both of these.

**Comment by ttocsneb** [comment]
The Crate.toml already has MIT set as its license. I will make sure that proper LICENSE files are added to the repo and I'm going to change it to include Apache-2.0.

**Comment by tryoxiss** [comment]
Ahhh ok, I must have missed that, sorry.

**Comment by ttocsneb** [comment]
It's all good, I should have the license be more than just in the Cargo.toml file, I just added it in [3523d0](https://github.com/ttocsneb/mbon/commit/3523d0d0f8c63c974c030ddf239d56ada6a562f3)

**Comment by tryoxiss** [comment]
Seems good!
